name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} 
        username: ${{ secrets.EC2_USER }}  
        key: ${{ secrets.SSH_PRIVATE_KEY }}  

    - name: GitClone repository
      run: git clone https://github.com/movvamanoj/hello_django.git ./django_project

    - name: Install dependencies (create virtual environment)
      run: |
        sudo apt update -y 
        sudo apt install python3-venv -y  

    - name: Create virtual environment
      run: python3 -m venv ./venv

    - name: Activate virtual environment
      run: source ./venv/bin/activate

    - name: Install project dependencies (within virtual environment)
      run: |
        cd ./django_project
        pip install -r requirements.txt

    - name: Run migrations 
      run: |
        cd ./django_project
        python3 manage.py migrate

    - name: Start Django in background
      run: |
        nohup python3 manage.py runserver 0.0.0.0:8000 &










# name: Deploy to Ubuntu EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: SSH into EC2 and deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }} 
#           username: ${{ secrets.EC2_USER }}  
#           key: ${{ secrets.SSH_PRIVATE_KEY }} 
#           script: |
#             git clone https://github.com/movvamanoj/hello_django.git
#             sudo apt update -y 
#             sudo apt install python3-venv -y  
#             python3 -m venv ./venv
#             source ./venv/bin/activate
#             cd hello_django
#             pip install -r requirements.txt
#             python3 manage.py migrate
#             nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
