name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            # Update system packages
            sudo apt update -y 

            # Install Python virtual environment
            sudo apt install python3-venv -y  

            # Clone the repository
            if [ -d "hello_django" ]; then
              cd hello_django
              git pull
            else
              git clone https://github.com/movvamanoj/hello_django.git
              cd hello_django
            fi

            # Set up Python virtual environment
            if [ -d "venv" ]; then
              source venv/bin/activate
            else
              python3 -m venv venv
              source venv/bin/activate
            fi

            # Install project dependencies
            pip install -r requirements.txt

            # Run Django migrations
            python3 manage.py migrate

            # Kill any existing Django processes
            pkill -f runserver

            # Start Django server in the background
            nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
