name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: GitClone repository
        run: git clone https://github.com/movvamanoj/hello_django.git ./django_project

      - name: Install dependencies (create virtual environment)
        run: |
          sudo apt update -y 
          sudo apt install python3-venv -y  
          python3 -m venv ./venv

      - name: Install project dependencies (within virtual environment)
        run: |
          source ./venv/bin/activate
          cd ./django_project
          pip install -r requirements.txt

      - name: Run migrations 
        run: |
          source ./venv/bin/activate
          cd ./django_project
          python manage.py migrate

      - name: Start Django server using Supervisor
        run: |
          sudo apt-get install supervisor -y
          sudo cp ./django_project/deploy/supervisor_django.conf /etc/supervisor/conf.d/
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl restart django

