name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository
        run: git clone https://github.com/movvamanoj/hello_django.git ./django_project

      - name: Install dependencies (create virtual environment)
        run: |
          sudo apt update -y 
          sudo apt install python3-venv -y  

      - name: Create virtual environment
        run: python3 -m venv ./venv

      - name: Activate virtual environment
        run: source ./venv/bin/activate

      - name: Install project dependencies (within virtual environment)
        run: |
          cd ./django_project
          pip install -r requirements.txt

      - name: Run migrations 
        run: |
          python3 manage.py migrate

      # - name: Start Django (modify for production use)
      #   run: |
      #     # Replace with a production server command like gunicorn
      #     python3 manage.py runserver 0.0.0.0:8000
      - name: Start Django in background
        run: |
          nohup python3 manage.py runserver 0.0.0.0:8000 &
