name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone repository
      run: git clone https://github.com/movvamanoj/hello_django.git ./django_project

    - name: Install Python dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv

    - name: Setup Python virtual environment
      run: |
        cd ./django_project
        python3 -m venv venv

    - name: Activate virtual environment and install project dependencies
      run: |
        cd ./django_project
        source ./venv/bin/activate
        pip install -r requirements.txt

    - name: Run migrations and collect static files
      run: |
        cd ./django_project
        source ./venv/bin/activate
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Start uWSGI server
      run: |
        cd ./django_project
        source ./venv/bin/activate
        ./venv/bin/uwsgi --http :8000 --module hello_django.wsgi
