name: Continuous Integration and Deployment (Ubuntu EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          entryPoint: sonar-scanner
          args: -Dsonar.projectKey=hello_django -Dsonar.organization=JHC -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

      - name: Deploy to Ubuntu EC2 (if SonarQube analysis succeeds)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          if: ${{ steps.analyze.outputs.success }}
          script: |
            git clone https://github.com/movvamanoj/hello_django.git
            sudo apt update -y
            sudo apt install python3-venv -y
            python3 -m venv ./venv
            source ./venv/bin/activate
            cd hello_django
            pip install -r requirements.txt
            python3 manage.py migrate
            nohup python3 manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
