name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv gunicorn nginx

    - name: Install project dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and collect static files
      run: |
        cd $GITHUB_WORKSPACE
        python3 manage.py migrate
        python3 manage.py collectstatic --no-input

    - name: Configure Nginx
      run: |
        sudo tee /etc/nginx/sites-available/my_django_app <<EOF
        server {
            listen 80;
            server_name example.com;

            location = /favicon.ico { access_log off; log_not_found off; }
            location /static/ {
                root $GITHUB_WORKSPACE;
            }

            location / {
                proxy_pass http://174.129.229.240:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
        EOF

    - name: Enable Nginx site
      run: |
        sudo ln -s /etc/nginx/sites-available/my_django_app /etc/nginx/sites-enabled

    - name: Test Nginx configuration
      run: sudo nginx -t

    - name: Restart Nginx
      run: sudo systemctl restart nginx

    - name: Start Django with Gunicorn
      run: |
        cd $GITHUB_WORKSPACE
        nohup gunicorn hello_django.wsgi:application &
