name: Deploy to Ubuntu EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone repository
      run: git clone https://github.com/movvamanoj/hello_django.git ./django_project

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv

    - name: Install project dependencies
      run: |
        cd ./django_project
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and collect static files
      run: |
        cd ./django_project
        python3 manage.py migrate
        python3 manage.py collectstatic --no-input

    - name: Start Django with Gunicorn
      run: |
        cd ./django_project
        sudo apt-get install -y gunicorn
        nohup gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000 &